import os

#Clears up the user-interface
def clear():
    os.system('cls||clear')

def how_to_use():
    #The info
    print("""1---See how to use this program: Basic info about the program, altough the information is kinda meh

2---Create a Password: Creates a password, you can choose how many uppercase and lowercase letters you want invidualy, 
    and then you chose how many numbers you want (0 - 9)
    then how many of these @ ! $ # symbols it should contain,
    And lastly, you can Add what ever you heart desires

3---Create a Pincode: You can choose the length of the pincode

4---Create an Encryption Key: You will create a key with 128-bit AES encryption in CBC mode, PKCS7 padding, it will be placed in the fodler where you have all the program files
    You will get to choose the files name, and it teh program will automatically make it a .key file (You don't need to install anything for .key files)

5---See Database: From this part you will be able to see and edit the database trough the program.
    Removing trough the program is kinda wonky at first, but it very simple, it will look something like this
    ['0This is the database', '1-----------------------', '2', '3TESTPASSWORD1', '4TESTPASSWORD2', '5TESTPASSWORD3', '6TESTPASSWORD4', '7TESTPASSWORD5']
    The number at the start of each things is the row, you don't have to ad that, it is done automaticaly by the program, 
    So to remove for example TESTPASSWORD3 you'd type 3 and hit enter in the ''remove from the database'' option
    Other than that, the database is pretty self explanitory.

6---Encrypt a file: This option will allow you to encrypt a file using akey generated by the programs 4:th option, 
    you can choose to have only a enrcypted file, or to have a un-encrypted copy along side the encrypted one

7---Decrypt a file: You can decrypt AES encrypted files aslong as you have the key used to encrypted them, 
    here you will get a Un-encrypted copy of the file, the original will remain encrypted

8---Stop the program: I bet you can't guess what this one does""")
    
    print('\n')
    #This loop lets you leave this file when you want to
    while True:
        exit = input('Press enter to exit to main menu')
        print('---------------------------\n')
        if exit == 0:
            clear()
            break
        else:
            clear()
            break